### ISSUE TITLE
Feature - Tooltip show upcoming raid resets

### ISSUE THREAD

**Issue by obstrom** [obstrom/TitanRaidLockout#13]
I as player, who has a main raid and sometimes a random raid, want to see the next Reset of 20er raids (ZG, AQ20). Also if i have a clear ID i want to see, if i can use actual ID with a random group before my next main raid occurs.

_Originally posted by @Scanda85 in https://github.com/obstrom/TitanRaidLockout/issues/2#issuecomment-683589462_

**Comment by obstrom** [comment]
Thanks for the feature request @Scanda85 👍🏻 

Just so I understand the request properly. You want the addon tooltip to display something like this, yes? For **all** raids.
| Instance Name [Bosses] | Reset Time | Following Reset Time |
| -------- | ------------- | ------------- |
| Blackwing Lair [8/8] | Wed 02/09 09:00 | Wed 09/09 09:00  |
| Zul'Gurub [8/10] | Sat 29/08 09:00 | Tue 01/09 09:00  |
| Molten Core [Open] | Wed 02/09 09:00 | Wed 09/09 09:00  |
| Onyxia's Lair [Open] | Tue 01/09 09:00 | Sun 06/09 09:00  |
| Ruins of Ahn'Qiraj [Open] | Sat 29/08 09:00 | Tue 01/09 09:00  |
| Ahn'Qiraj [Open] | Wed 02/09 09:00 | Wed 09/09 09:00  |

The above is possible and I could certainly make it a menu setting you'd first have to enable to see (like "Show detailed reset information"). However these looks to be quite finicky to achieve.

**Implementation reasoning:** At the moment the addon only displays reset times of raids you are locked into, that is because that is the only information I can get out of the games built in functions (API) at the moment. Infact I only get seconds remaining until a locked instance is reset. I calculate that into a specific date to display when it resets.

If I were to display when a raid resets that you are *not* locked into, I would have to try and estimate that date. It would be hard to get it to be reliably accurate. Especially since realms in different regions have different reset dates. I will have to research how exact the reset pattern in - I know it is possible since services like Wowhead do predict reset times.

**Conclusion:** Might be difficult to implement, but certainly possible. I will take a look at it after completing other more pressing features.

**Comment by Scanda85** [comment]
yes thats correct.
