### ISSUE TITLE
Colour of active AQ40 id is not "red" (german UI)

### ISSUE THREAD

**Issue by Scanda85** [obstrom/TitanRaidLockout#14]
I have an active AQ40 ID, but "AQ40" is still with green colour.
![image](https://user-images.githubusercontent.com/20796795/91749014-30503600-ebc1-11ea-920f-bee53338078a.png)

Also with /reload problem still occurs

German client 
Addon version 1.0.2

**Comment by obstrom** [comment]
Thanks for the report! 👍🏻 

I see the cause of the issue straight away. I updated the [development build](https://github.com/obstrom/TitanRaidLockout/archive/develop.zip) with a hotfix you can use now to fix the issue if you want.

**Why this is occuring:** Unfortunately, for the abbreviation colors to work I need the exact name of the instance the game API uses. This name gets changed with localization and there is no "instance number" or such I can use instead. I looked at Wowhead for instance name translations into German, French, Spanish and Russian and it seems they did not exactly match the names Blizzard uses in the game API.

**Comment by Scanda85** [comment]
Looks good:
![image](https://user-images.githubusercontent.com/20796795/91754356-8fb24400-ebc9-11ea-8b4a-ffb3d0ccdd76.png)

**Comment by obstrom** [comment]
Issue fixed with live [version release 1.0.3](https://github.com/obstrom/TitanRaidLockout/releases/tag/v1.0.3)
