### ISSUE TITLE
Add support for Mgt and H Mgt and Sunwell Plateau

### ISSUE THREAD

**Issue by mtoedtem** [obstrom/TitanRaidLockout#24]
Currently does not support Magister's Terrace (Normal or Heroic) or Sunwell Plateau.

**Comment by cezeta** [comment]
edit file TitanRaidLockout.lua and uncomment lines 41, 59, 79, 375 and 388 :-)

**Comment by mtoedtem** [comment]
Thanks for the info.

**Comment by obstrom** [comment]
Hi! Thanks for the feedback @mtoedtem.

I'm no longer playing and thus not actively supporting this addon with updates. However I planned ahead at the launch of TBC and added all the upcoming dungeons and raids of the expansion to the addon as a disabled feature. However I could never really test that they were working correctly.

@cezeta If simply uncommenting those lines are working fine for you, then I can push an update with that to Github and Curseforge. Could you or another kind soul please verify that things are still working in-game then?

Thanks for the assistance.

**Comment by cezeta** [comment]
I can confirm that it works - I was just ingame checking that everything is OK:
![image](https://user-images.githubusercontent.com/935314/169914523-dafe8fef-4016-4697-a48c-3e596dac1220.png)

**Comment by mtoedtem** [comment]
Can confirm. Works as intended.

**Comment by obstrom** [comment]
Great! Thanks for the help.

I'm working on bumping the version to 1.2.1 now and doing a new release to Github and Curse now. Should be live shortly.

Sorry for the delay.
