### ISSUE TITLE
WoTLK raid difficulty (10/25 man)

### ISSUE THREAD

**Issue by obstrom** [obstrom/TitanRaidLockout#29]
A raid can be done in either 10 or 25-man difficulty, and each has its own separate lockout it seems?

If the [GetNumSavedInstances](https://wowpedia.fandom.com/wiki/API_GetNumSavedInstances) still returns one entry for each difficulty (and not a single entry for either/both) then it should be possible to handle this. Looking at [GetSavedInstanceInfo](https://wowpedia.fandom.com/wiki/API_GetSavedInstanceInfo) it returns a `difficulty` and `difficultyName` value. These values did not work and were skipped in classic/TBC-era, but might work as intended now in WoTLK and could perhaps be used to fix this.

Will need help with testing any alpha/beta build I make for this.

**Comment by raimondi1337** [comment]
Came here to ask for this, ping if you need testing help

**Comment by 1Botnet** [comment]
I am willing to help with this as well

**Comment by margathon** [comment]
added checks for difficulty in raids (3 = 10man, 4 = 25man)
https://github.com/margathon/TitanRaidLockout/blob/master-wotlk/TitanRaidLockout.lua

**Comment by 1Botnet** [comment]
Working nicely. No LUA errors.

**Comment by obstrom** [comment]
Hey, thanks for the swift PR @margathon- great work! I've merged PR #30 and I'll publish a v1.3.1 release with this right away.

Also thanks for the help again with testing @1Botnet. Great feedback!
