### ISSUE TITLE
Non-WotLK raids not showing

### ISSUE THREAD

**Issue by obstrom** [obstrom/TitanRaidLockout#35]
The changes done with PR #34 for Issue #32 with v1.3.2 seem to have effected non-WotLK raids, going by [this comment](https://www.curseforge.com/projects/404951?comment=21).

This is probably due to the change using `maxPlayer` affecting Classic and TBC raids as well. Since 10/25 is not applicable with these raids likely causing this bug. Using `difficultyId` instead and then mapping it to the correct raid size [using this table](https://wowpedia.fandom.com/wiki/DifficultyID#Classic), or using one of the raidDifficulty helper functions, might work better for this.

I'll have a look a making a fix and pushing a new beta build to be tested asap.

**Comment by Ropid** [comment]
I'm seeing the same problem as in that comment you linked to. Doing Karazhan and Zul-Gurub every week, and Karazhan is not showing up, while Zul-Gurub is fine. I was also in Molten Core this week, and Molten Core shows up fine as well.

I think this problem is actually older than just Jan 22 release. I'm pretty sure I've already seen this in December. This would mean it's not those #34 Ulduar changes and it was already a bug in at least the Oct 25 release?

**Comment by obstrom** [comment]
@Ropid Ah yes, you're correct! This issue seems to have been introduced with #30, so it's been present since Oct 25 then. There was a check present in the code for 10 and 25-man raids which seems to have not taking into consideration other 10 and 25 man raids that are non-WotLK raids like Karazhan. Hence why it did not effect Zul-Gurub (20) or Molten Core (40).

**Comment by obstrom** [comment]
I have pushed a new beta build (v.1.3.3-b01) to CurseForge now which should hopefully fix this. I would greatly appreciate it someone could test it out and report back! 🙏🏻

**Comment by Ropid** [comment]
With the beta version you mention, I get errors when I `/reload`. Opening TitanRaidLockOut.lua, it seems there's content missing at the end at line 757. There's a function definition starting there and then nothing.

**EDIT:**

I removed that empty function on line 756 in TitanRaidLockout.lua and got no errors and the tooltip seems to work correctly. I visited Zul-Gurub and Karazhan and did a few bosses there. Karazhan shows up now.

**Comment by obstrom** [comment]
Oh no- how silly! 🙈 Sorry about that @Ropid. Great to hear that it was working otherwise when you removed the empty function.

I've uploaded a new beta version now where I have fixed the above mentioned issue. I have also made an addition where I worked on #36 adding a settings toggle to show or hide raid size in the panel text.

**Comment by Ropid** [comment]
There's now a bug where it doesn't show the locked raids in the panel text. It shows no text in the panel by default. If I select "show unlocked" in the right-click menu, I can see my locked raids like ULD25 etc. show as a green color.

I don't know if this is a new bug in version ...-b02 or if it was already there in ...-b01. I tried going back to the release channel and with that version it shows locked raids correctly in red text in the panel.

I also tried using the "delete settings (saved variables)" option in the CurseForge program but that didn't help.

**Comment by obstrom** [comment]
Sorry for the delay. I think I have found the issue and fixed it now. There's a new beta version `b03` on CurseForge now.

@Ropid Yeah, in my attempt to fix how it displays the raids in the panel texts I introduced a bug in b01 and b02. Hopefully it should be working as intended now.

**Comment by Ropid** [comment]
I think there's a bunch of `end` missing on single-line if-then-else constructs, though I don't know anything about LUA really.

I got this confusing error at first:

```
TitanRaidLockout/TitanRaidLockout.lua:564: 'end' expected (to close 'for' at line 557) near 'else'
```

Looking around a bit, I then tried adding an `end` to line 560. After adding that, I got a strange error about the last line 769 of the file. After looking around the file for a while, I think the problems are in lines 512, 533, 552, 560, 592, 610. I added an `end` to all of those lines, and things seem to work now.

Here's links to the lines I mean:

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L512

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L533

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L552

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L560

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L592

https://github.com/obstrom/TitanRaidLockout/blob/d5c21b0063b92b565a27a3986867fc8918fc73e9/TitanRaidLockout.lua#L610

I hope those are all lines I edited here locally. I might have forgotten one of them.

**Comment by Ropid** [comment]
After fixing the file like mentioned previously, there's some bug happening for the panel text. It seems to get confused about the 10 and 25 sizes for the same raid.

On one character here, I went to the following raids according to the tooltip text:

- Zul'Gurub (20)
- Vault of Archavon (25)
- Vault of Archavon (10)
- Ulduar (10)
- Naxxramas (10)

With options "show 10-man raids" and "show raid size in abbreviations" enabled, I get the following panel text result:

```NAXX10 ULD10 VoA10 VoA10 NAXX25 ULD25 VoA25 VoA25```

If I disable option "show 10-man raids", I get this panel text:

```NAXX25 ULD25 VoA25 VoA25```

If I then also disable raid size abbreviations, I get this, all colored in red:

```NAXX ULD VoA VoA```

With size abbreviations enabled, but "show 10-man raids" enabled, I get, with orange color for first half of text, and red color for second half:

```NAXX ULD VoA VoA NAXX ULD VoA VoA```

**Comment by obstrom** [comment]
Thanks alot for the assistance and for your patients with my revisions @Ropid 🙏🏻

 I've uploaded a new `b04` to CurseForge. Hopefully I got everything right this time.

Indeed, I had missed adding `end` on a few lines. Coming from Java and JavaScript I never really get used to the `if ... then ... end` syntax of Lua. I got a Lua linter up and running now with my IDE so hopefuly I will avoid such silly syntax errors going forward.

As for the other issue I had forgotten to check whether a raid was 10 or 25-man before printing the panel text, thus them showing up twice. Should be fixed now aswell.

**Comment by Ropid** [comment]
I just tried b04 and it seems to work perfectly. I tried disabling and enabling all of the options in the right-click menu and all seem to work.

I downloaded the b04 version here from Github. The file didn't show up at Curseforge for me. This here was the exact version I tried:

https://github.com/obstrom/TitanRaidLockout/tree/9104234382674a8b49ae5fd47d4217bf3f2bfeea

**Comment by obstrom** [comment]
Perfect, thanks again for the help! I'll make a release version of this then 🙌🏻 

It seems `b04` is stuck as still under review on CurseForge.
