### ISSUE TITLE
10 man raid lockout disappears upon the logout

### ISSUE THREAD

**Issue by djkroo** [obstrom/TitanRaidLockout#38]
10 man raid lockout disappears upon the logout. Every time you log on you have to re-enable 10 man lockout.

**Comment by obstrom** [comment]
Hi, thanks for reporting this @djkroo!

I believe I've found and fixed the issue. I've uploaded a new beta version to the [CurseForge project](https://legacy.curseforge.com/wow/addons/titan-panel-classic-raid-lockout) which should be available shortly. 

Alternatively you can download the zip of the beta build manually from the [dev-wotlk-1.3.4 branch](https://github.com/obstrom/TitanRaidLockout/tree/dev-wotlk-1.3.4) if you want to try it out, just remeber to rename the extracted folder to `TitanRaidLockout`.

I would be grateful if you, or someone else, could get back to me whether this build solved the issue. Thanks 🙏🏻

**Comment by djkroo** [comment]
Thank you so much! <3
