### ISSUE TITLE
can't see TotC on bar

### ISSUE THREAD

**Issue by masterkain** [obstrom/TitanRaidLockout#40]
![Screenshot 2023-09-09 154429](https://github.com/obstrom/TitanRaidLockout/assets/12844/97cab87a-08b4-46cb-97d3-9f65a810a301)

**Comment by obstrom** [comment]
Hi, thanks @masterkain for reporting this!

I found an issue with how TotC is setup in the addon which might be the cause of this bug. I've pushed a new beta version, `1.3.5 beta01` to CurseForge. You need to have beta versions enabled in your addon manager, or download it manually. Would you be able to download this beta version and test if the changes I've made solves this issue?

Thanks for the help!

**Comment by masterkain** [comment]
thanks for the update, it seems to work 👍

**Comment by obstrom** [comment]
Great, thanks for the help @masterkain! 

I'll push a new release version to CurgeForge then shortly.
